openapi: 3.0.1
info:
  title: fake-millionaire-server
  description: Fake-Millionaire-Server
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: Millionaire
    description: Returning best points in time for buying/selling stocks
  - name: Specification
    description: The swagger API specification
paths:
  /millionaire:
    get:
      tags:
        - Millionaire
      description: By given time slice, fetch two points in time for best buy/sell options
      parameters:
        - name: start
          in: query
          description: Start date-time
          required: true
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: End date-time
          required: true
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Return the two points in time with their price equivalent
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
